artifact_location: /Users/matthiasmotl/neuefische/repositories/dtc/dtc-mlops/02_experiment_tracking/sqlite/mlflow.db/0
creation_time: 1747389893938
experiment_id: '0'
last_update_time: 1747389893938
lifecycle_stage: active
name: Default
