artifact_location: /Users/matthiasmotl/neuefische/repositories/dtc/dtc-mlops/02_experiment_tracking/sqlite/mlflow.db/361364565729454174
creation_time: 1747389893943
experiment_id: '361364565729454174'
last_update_time: 1747389893943
lifecycle_stage: active
name: MLflow Iris
